apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-kubernetes-demo
spec:
  selector:
    matchLabels:
      run: laravel-kubernetes-demo
  template:
    metadata:
      labels:
        run: laravel-kubernetes-demo
    spec:
      containers:
        - name: demo
          image: absolutezero24/laravel-kubernetes-demo:v1.1
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-kubernetes-demoservice
spec:
  selector:
    run: laravel-kubernetes-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer