---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laravel-kubernetes-demo-ingress
spec:
  rules:
  - host: laravel-kubernetes.demo
  - http:
      paths:
      - backend:
          serviceName: laravel-kubernetes-demo-service
          servicePort: 80
        path: ./public